### ISSUE TITLE
Running db:update does not store all of the rules in the database

### ISSUE THREAD

**Issue by FelixBole** [Prometheus-X-association/catalog-registry#6]
**Describe the bug**
When running db:init or db:update, most references are correctly stored but rules seem to have an issue where after the first one stored, it doesn't store any other.

**To Reproduce**
1. run `npm run db:init` or `npm run db:update`
2. check database
**Expected behavior**
Should store all references including rules

**Screenshots**
![image](https://github.com/Prometheus-X-association/catalog-registry/assets/54702474/e63a2206-e6c4-420f-a718-029154682379)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Visions-Nicolas** [comment]
Fixed with the featuring #7
